CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(320) NOT NULL,
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(1000) NOT NULL,
  available BOOLEAN DEFAULT true,
  owner_id BIGINT NOT NULL REFERENCES users (id) ON DELETE RESTRICT ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  item_id BIGINT NOT NULL REFERENCES items (id) ON DELETE RESTRICT ON DELETE CASCADE,
  booker_id BIGINT NOT NULL REFERENCES users (id) ON DELETE RESTRICT ON DELETE CASCADE,
  start_booking TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  end_booking TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'WAITING'
);

CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  item_id BIGINT NOT NULL REFERENCES items (id) ON DELETE RESTRICT ON DELETE CASCADE,
  author_id BIGINT NOT NULL REFERENCES users (id) ON DELETE RESTRICT ON DELETE CASCADE,
  text VARCHAR(1000) NOT NULL,
  created TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);