DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS requests;
DROP TABLE IF EXISTS users;


CREATE TABLE IF NOT EXISTS users ( id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(320) NOT NULL,
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  description VARCHAR(1000) NOT NULL UNIQUE,
  requester_id BIGINT NOT NULL,
  created TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

ALTER TABLE requests ADD FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS items (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(1000) NOT NULL,
  available BOOLEAN DEFAULT true,
  owner_id BIGINT NOT NULL,
  request_id BIGINT
);
ALTER TABLE items ADD FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE items ADD FOREIGN KEY (request_id) REFERENCES requests (id) ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  item_id BIGINT NOT NULL,
  author_id BIGINT NOT NULL,
  text VARCHAR(1000) NOT NULL,
  created TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

ALTER TABLE comments ADD FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE comments ADD FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE;


CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  item_id BIGINT NOT NULL,
  booker_id BIGINT NOT NULL,
  start_booking TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  end_booking TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'WAITING'
);

ALTER TABLE bookings ADD FOREIGN KEY (booker_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE bookings ADD FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE;
